SDB: sdb.h File Reference
sdb.h File Reference
Simple Database Library.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
Data Structures
struct SDBEntry
struct SDBEntryList
struct SDBTable
struct SDB
struct SDBOperation
struct SDBPool
struct SDBInfo
Macros
#define SDB_VERSION "0.4.0"
#define WINDOW_SIZE 1024
#define MIN_MATCH 3
#define POOL_BLOCK_SIZE 4096
#define SDB_MAGIC 0x53444246
#define SDB_FILE_VERSION 1
Typedefs
typedef struct SDBEntry SDBEntry
Enumerations
enum SDBCompressType { SDB_COMPRESS_NONE , SDB_COMPRESS_RLE , SDB_COMPRESS_LZ77 }
Functions
static void write_to_buffer (unsigned char **buffer, size_t *buffer_size, size_t *current_size, const void *data, size_t size)
Helper function to write data to a buffer with automatic resizing.
static size_t hash_string (const char *str)
static unsigned char * rle_compress (const unsigned char *data, size_t data_len, size_t *out_len)
Compresses data using run-length encoding.
static unsigned char * rle_decompress (const unsigned char *compressed, size_t comp_len, size_t *out_len)
Decompresses RLE compressed data.
static unsigned char * lz77_compress (const unsigned char *data, size_t data_len, size_t *out_len)
Compresses data using LZ77-style compression.
static unsigned char * lz77_decompress (const unsigned char *compressed, size_t comp_len, size_t *out_len)
Decompresses LZ77 compressed data.
SDB * sdb_open (const char *path, SDBCompressType compress_type)
Opens a database file.
void sdb_close (SDB *sdb)
Closes the database.
void sdb_save (SDB *sdb)
Saves the database.
void sdb_table_create (SDB *sdb, const char *name)
Creates a table in the database.
void sdb_table_destroy (SDB *sdb, const char *name)
Destroys a table in the database.
SDBTable * sdb_table_find (SDB *sdb, const char *name)
Finds a table in the database.
void sdb_table_set (SDB *sdb, const char *table, const char *key, const char *value)
Sets a value in the database.
char * sdb_table_get (SDB *sdb, const char *table, const char *key)
Gets a value from the database.
void sdb_batch_execute (SDB *sdb, SDBOperation *ops, size_t count)
static SDBInfo sdb_info (SDB *sdb)
void sdb_free_info (SDBInfo info)
Detailed Description
Simple Database Library.
Version
0.4.0
This is a simple database library that is used to store data in a file. It is not meant to be a full-featured database, but rather a simple way to store data.
Author
Johannes (Jotrorox) Müller
Copyright
Copyright (c) 2024
Definition in file sdb.h.
Macro Definition Documentation
MIN_MATCH
#define MIN_MATCH 3
Definition at line 26 of file sdb.h.
POOL_BLOCK_SIZE
#define POOL_BLOCK_SIZE 4096
Definition at line 27 of file sdb.h.
SDB_FILE_VERSION
#define SDB_FILE_VERSION 1
Definition at line 29 of file sdb.h.
SDB_MAGIC
#define SDB_MAGIC 0x53444246
Definition at line 28 of file sdb.h.
SDB_VERSION
#define SDB_VERSION "0.4.0"
Definition at line 24 of file sdb.h.
WINDOW_SIZE
#define WINDOW_SIZE 1024
Definition at line 25 of file sdb.h.
Typedef Documentation
SDBEntry
typedef struct SDBEntry SDBEntry
Enumeration Type Documentation
SDBCompressType
enum SDBCompressType
Enumerator
SDB_COMPRESS_NONE
SDB_COMPRESS_RLE
SDB_COMPRESS_LZ77
Definition at line 34 of file sdb.h.
              {
     SDB_COMPRESS_NONE,
     SDB_COMPRESS_RLE,
     SDB_COMPRESS_LZ77
 } SDBCompressType;
Function Documentation
hash_string()
static size_t hash_string (const char * str) static
Definition at line 668 of file sdb.h.
{
     size_t hash = 5381;
     int c;
     while ((c = *str++))
         hash = ((hash << 5) + hash) + c;
     return hash;
 }
Referenced by sdb_table_set().
lz77_compress()
static unsigned char* lz77_compress (const unsigned char * data, size_t data_len, size_t * out_len) static
Compresses data using LZ77-style compression.
Parameters
data Input data to compress
data_len Length of input data
out_len Pointer to store compressed length
Returns
Compressed data buffer
Definition at line 173 of file sdb.h.
{
     unsigned char* compressed = (unsigned char*)malloc(data_len * 2);
     size_t comp_pos = 0;
     for (size_t i = 0; i < data_len;) {
         size_t best_len = 0;
         size_t best_offset = 0;
         // Search in sliding window
         size_t window_start = (i > WINDOW_SIZE) ? i - WINDOW_SIZE : 0;
         for (size_t j = window_start; j < i; j++) {
             size_t len = 0;
             while (i + len < data_len &&
                    j + len < i &&
                    data[i + len] == data[j + len] &&
                    len < 255) {
                 len++;
             }
             if (len > best_len) {
                 best_len = len;
                 best_offset = i - j;
             }
         }
         if (best_len >= MIN_MATCH) {
             compressed[comp_pos++] = 1;  // Flag for match
             compressed[comp_pos++] = best_offset & 0xFF;
             compressed[comp_pos++] = (best_offset >> 8) & 0xFF;
             compressed[comp_pos++] = best_len;
             i += best_len;
         } else {
             compressed[comp_pos++] = 0;  // Flag for literal
             compressed[comp_pos++] = data[i++];
         }
     }
     *out_len = comp_pos;
     return realloc(compressed, comp_pos);
 }
References MIN_MATCH, and WINDOW_SIZE.
Referenced by sdb_save().
lz77_decompress()
static unsigned char* lz77_decompress (const unsigned char * compressed, size_t comp_len, size_t * out_len) static
Decompresses LZ77 compressed data.
Parameters
compressed Compressed input data
comp_len Length of compressed data
out_len Pointer to store decompressed length
Returns
Decompressed data buffer
Definition at line 223 of file sdb.h.
{
     if (!compressed || comp_len == 0) return NULL;
     unsigned char* decompressed = (unsigned char*)malloc(comp_len * 2); // Initial size estimate
     size_t decom_pos = 0;
     size_t pos = 0;
     while (pos < comp_len) {
         if (compressed[pos] == 0) { // Literal
             decompressed[decom_pos++] = compressed[pos + 1];
             pos += 2;
         } else { // Match
             size_t offset = compressed[pos + 1] | (compressed[pos + 2] << 8);
             size_t length = compressed[pos + 3];
             for (size_t i = 0; i < length; i++) {
                 decompressed[decom_pos] = decompressed[decom_pos - offset];
                 decom_pos++;
             }
             pos += 4;
         }
     }
     *out_len = decom_pos;
     return realloc(decompressed, decom_pos);
 }
Referenced by sdb_open().
rle_compress()
static unsigned char* rle_compress (const unsigned char * data, size_t data_len, size_t * out_len) static
Compresses data using run-length encoding.
Parameters
data Input data to compress
data_len Length of input data
out_len Pointer to store compressed length
Returns
Compressed data buffer
Definition at line 102 of file sdb.h.
{
     if (!data || data_len == 0) return NULL;
     // Allocate worst case size (input size * 2)
     unsigned char* compressed = (unsigned char*)malloc(data_len * 2);
     if (!compressed) return NULL;
     size_t comp_pos = 0;
     size_t pos = 0;
     while (pos < data_len) {
         unsigned char count = 1;
         unsigned char current = data[pos];
         while (pos + count < data_len &&
                data[pos + count] == current &&
                count < 255) {
             count++;
         }
         compressed[comp_pos++] = count;
         compressed[comp_pos++] = current;
         pos += count;
     }
     *out_len = comp_pos;
     return realloc(compressed, comp_pos); // Shrink to actual size
 }
Referenced by sdb_save().
rle_decompress()
static unsigned char* rle_decompress (const unsigned char * compressed, size_t comp_len, size_t * out_len) static
Decompresses RLE compressed data.
Parameters
compressed Compressed input data
comp_len Length of compressed data
out_len Pointer to store decompressed length
Returns
Decompressed data buffer
Definition at line 139 of file sdb.h.
{
     if (!compressed || comp_len == 0) return NULL;
     // First pass: calculate decompressed size
     size_t decom_size = 0;
     for (size_t i = 0; i < comp_len; i += 2) {
         decom_size += compressed[i];
     }
     unsigned char* decompressed = (unsigned char*)malloc(decom_size);
     if (!decompressed) return NULL;
     size_t pos = 0;
     for (size_t i = 0; i < comp_len; i += 2) {
         unsigned char count = compressed[i];
         unsigned char value = compressed[i + 1];
         for (unsigned char j = 0; j < count; j++) {
             decompressed[pos++] = value;
         }
     }
     *out_len = decom_size;
     return decompressed;
 }
Referenced by sdb_open().
sdb_batch_execute()
void sdb_batch_execute (SDB * sdb, SDBOperation * ops, size_t count)
Definition at line 635 of file sdb.h.
{
     for (size_t i = 0; i < count; i++) {
         sdb_table_set(sdb, ops[i].table, ops[i].key, ops[i].value);
     }
     // Single save at the end
     sdb_save(sdb);
 }
References sdb_save(), and sdb_table_set().
sdb_close()
void sdb_close (SDB * sdb)
Closes the database.
Parameters
sdb The database
Definition at line 385 of file sdb.h.
{
     if (!sdb) return;
     // Free all tables and their entries
     for (int i = 0; i < sdb->table_count; i++) {
         // Free all entries in the table
         SDBEntry* current = sdb->tables[i].entries->head;
         while (current != NULL) {
             SDBEntry* next = current->next;
             free(current->key);
             free(current->value);
             free(current);
             current = next;
         }
         // Free table structure
         free(sdb->tables[i].name);
         free(sdb->tables[i].entries);
     }
     // Free tables array
     free(sdb->tables);
     // Free path
     free(sdb->path);
     // Finally free the SDB structure
     free(sdb);
 }
References SDBTable::entries, SDBEntryList::head, SDBEntry::key, SDBTable::name, SDBEntry::next, SDB::path, SDB::table_count, SDB::tables, and SDBEntry::value.
Referenced by main().
sdb_free_info()
void sdb_free_info (SDBInfo info)
Definition at line 686 of file sdb.h.
{
     free(info.path);
     free(info.version);
     // Don't free compress_type as it's an enum
 }
References SDBInfo::path, and SDBInfo::version.
Referenced by main().
sdb_info()
static SDBInfo sdb_info (SDB * sdb) static
Definition at line 676 of file sdb.h.
{
     SDBInfo info = {0};
     if (sdb) {
         info.path = strdup(sdb->path);
         info.version = strdup(SDB_VERSION);
         info.compress_type = sdb->compress_type;
     }
     return info;
 }
References SDB::compress_type, SDBInfo::compress_type, SDB::path, SDBInfo::path, SDB_VERSION, and SDBInfo::version.
Referenced by main().
sdb_open()
SDB* sdb_open (const char * path, SDBCompressType compress_type)
Opens a database file.
Parameters
path The path to the database file
Returns
The database
Definition at line 259 of file sdb.h.
{
     SDB* sdb = (SDB*)malloc(sizeof(SDB));
     if (sdb == NULL) {
         return NULL;
     }
     sdb->path = strdup(path);
     sdb->tables = NULL;
     sdb->table_count = 0;
     sdb->compress_type = compress_type;
     FILE* file = fopen(path, "rb");
     if (file != NULL) {
         // Read and verify file header
         uint32_t magic, version;
         SDBCompressType stored_compress_type;
         if (fread(&magic, sizeof(uint32_t), 1, file) != 1 ||
             fread(&version, sizeof(uint32_t), 1, file) != 1 ||
             fread(&stored_compress_type, sizeof(SDBCompressType), 1, file) != 1) {
             fclose(file);
             return sdb;  // Return empty database if header read fails
         }
         // Verify magic number and version
         if (magic != SDB_MAGIC || version > SDB_FILE_VERSION) {
             fclose(file);
             return sdb;  // Return empty database if validation fails
         }
         // Use stored compression type if it exists
         sdb->compress_type = stored_compress_type;
         // Read compressed data
         size_t compressed_size, original_size;
         fread(&compressed_size, sizeof(size_t), 1, file);
         fread(&original_size, sizeof(size_t), 1, file);
         unsigned char* compressed = (unsigned char*)malloc(compressed_size);
         fread(compressed, 1, compressed_size, file);
         // Decompress data using the specified compression type
         size_t decompressed_size;
         unsigned char* buffer;
         if (compress_type == SDB_COMPRESS_RLE) {
             buffer = rle_decompress(compressed, compressed_size, &decompressed_size);
         } else {
             buffer = lz77_decompress(compressed, compressed_size, &decompressed_size);
         }
         free(compressed);
         if (buffer && decompressed_size == original_size) {
             size_t pos = 0;
             // Read table count
             memcpy(&sdb->table_count, buffer + pos, sizeof(int));
             pos += sizeof(int);
             if (sdb->table_count > 0) {
                 sdb->tables = (SDBTable*)malloc(sizeof(SDBTable) * sdb->table_count);
                 // Read each table
                 for (int i = 0; i < sdb->table_count; i++) {
                     int name_len;
                     memcpy(&name_len, buffer + pos, sizeof(int));
                     pos += sizeof(int);
                     sdb->tables[i].name = (char*)malloc(name_len + 1);
                     memcpy(sdb->tables[i].name, buffer + pos, name_len);
                     pos += name_len;
                     sdb->tables[i].name[name_len] = '\0';
                     sdb->tables[i].entries = (SDBEntryList*)malloc(sizeof(SDBEntryList));
                     sdb->tables[i].entries->head = NULL;
                     sdb->tables[i].entries->tail = NULL;
                     // Read entries
                     int entry_count;
                     memcpy(&entry_count, buffer + pos, sizeof(int));
                     pos += sizeof(int);
                     SDBEntry* current = NULL;
                     for (int j = 0; j < entry_count; j++) {
                         SDBEntry* entry = (SDBEntry*)malloc(sizeof(SDBEntry));
                         int key_len, value_len;
                         memcpy(&key_len, buffer + pos, sizeof(int));
                         pos += sizeof(int);
                         memcpy(&value_len, buffer + pos, sizeof(int));
                         pos += sizeof(int);
                         entry->key = (char*)malloc(key_len + 1);
                         entry->value = (char*)malloc(value_len + 1);
                         memcpy(entry->key, buffer + pos, key_len);
                         pos += key_len;
                         memcpy(entry->value, buffer + pos, value_len);
                         pos += value_len;
                         entry->key[key_len] = '\0';
                         entry->value[value_len] = '\0';
                         entry->next = NULL;
                         if (current == NULL) {
                             sdb->tables[i].entries->head = entry;
                         } else {
                             current->next = entry;
                         }
                         current = entry;
                     }
                     sdb->tables[i].entries->tail = current;
                 }
             }
             free(buffer);
         }
         fclose(file);
     }
     return sdb;
 }
References SDB::compress_type, SDBTable::entries, SDBEntryList::head, SDBEntry::key, lz77_decompress(), SDBTable::name, SDBEntry::next, SDB::path, rle_decompress(), SDB_COMPRESS_RLE, SDB_FILE_VERSION, SDB_MAGIC, SDB::table_count, SDB::tables, SDBEntryList::tail, and SDBEntry::value.
Referenced by main().
sdb_save()
void sdb_save (SDB * sdb)
Saves the database.
Parameters
sdb The database
Definition at line 420 of file sdb.h.
{
     FILE* file = fopen(sdb->path, "wb");
     if (file == NULL) {
         return;
     }
     // Write file header
     uint32_t magic = SDB_MAGIC;
     uint32_t version = SDB_FILE_VERSION;
     fwrite(&magic, sizeof(uint32_t), 1, file);
     fwrite(&version, sizeof(uint32_t), 1, file);
     fwrite(&sdb->compress_type, sizeof(SDBCompressType), 1, file);
     size_t buffer_size = 1024;  // Initial size
     size_t current_size = 0;
     unsigned char* buffer = (unsigned char*)malloc(buffer_size);
     // Write table count
     write_to_buffer(&buffer, &buffer_size, &current_size,
                    &sdb->table_count, sizeof(int));
     // Write each table
     for (int i = 0; i < sdb->table_count; i++) {
         // Write table name
         int name_len = strlen(sdb->tables[i].name);
         write_to_buffer(&buffer, &buffer_size, &current_size,
                        &name_len, sizeof(int));
         write_to_buffer(&buffer, &buffer_size, &current_size,
                        sdb->tables[i].name, name_len);
         // Count and write entries
         int entry_count = 0;
         SDBEntry* current = sdb->tables[i].entries->head;
         while (current != NULL) {
             entry_count++;
             current = current->next;
         }
         write_to_buffer(&buffer, &buffer_size, &current_size,
                        &entry_count, sizeof(int));
         // Write each entry
         current = sdb->tables[i].entries->head;
         while (current != NULL) {
             int key_len = strlen(current->key);
             int value_len = strlen(current->value);
             write_to_buffer(&buffer, &buffer_size, &current_size,
                            &key_len, sizeof(int));
             write_to_buffer(&buffer, &buffer_size, &current_size,
                            &value_len, sizeof(int));
             write_to_buffer(&buffer, &buffer_size, &current_size,
                            current->key, key_len);
             write_to_buffer(&buffer, &buffer_size, &current_size,
                            current->value, value_len);
             current = current->next;
         }
     }
     // Compress the buffer
     size_t compressed_size;
     unsigned char* compressed;
     if (sdb->compress_type == SDB_COMPRESS_RLE) {
         compressed = rle_compress(buffer, current_size, &compressed_size);
     } else {
         compressed = lz77_compress(buffer, current_size, &compressed_size);
     }
     // Write compressed size followed by compressed data
     fwrite(&compressed_size, sizeof(size_t), 1, file);
     fwrite(&current_size, sizeof(size_t), 1, file);  // Original size
     fwrite(compressed, 1, compressed_size, file);
     free(buffer);
     free(compressed);
     fclose(file);
 }
References SDB::compress_type, SDBTable::entries, SDBEntryList::head, SDBEntry::key, lz77_compress(), SDBTable::name, SDBEntry::next, SDB::path, rle_compress(), SDB_COMPRESS_RLE, SDB_FILE_VERSION, SDB_MAGIC, SDB::table_count, SDB::tables, SDBEntry::value, and write_to_buffer().
Referenced by sdb_batch_execute(), and sdb_table_set().
sdb_table_create()
void sdb_table_create (SDB * sdb, const char * name)
Creates a table in the database.
Parameters
sdb The database
name The name of the table
Definition at line 509 of file sdb.h.
{
     sdb->table_count++;
     sdb->tables = (SDBTable*)realloc(sdb->tables, sizeof(SDBTable) * sdb->table_count);
     // Initialize the new table
     SDBTable* table = &sdb->tables[sdb->table_count - 1];
     table->name = strdup(name);
     table->entries = (SDBEntryList*)malloc(sizeof(SDBEntryList));
     // Initialize hash table components
     table->entries->head = NULL;
     table->entries->tail = NULL;
     table->entries->capacity = 16;  // Initial capacity, can be adjusted
     table->entries->entries = (SDBEntry**)calloc(table->entries->capacity, sizeof(SDBEntry*));
 }
References SDBEntryList::capacity, SDBEntryList::entries, SDBTable::entries, SDBEntryList::head, SDBTable::name, SDB::table_count, SDB::tables, and SDBEntryList::tail.
Referenced by main().
sdb_table_destroy()
void sdb_table_destroy (SDB * sdb, const char * name)
Destroys a table in the database.
Parameters
sdb The database
name The name of the table
Definition at line 531 of file sdb.h.
{
     for (int i = 0; i < sdb->table_count; i++) {
         if (strcmp(sdb->tables[i].name, name) == 0) {
             free(sdb->tables[i].name);
             // Free entries
             SDBEntry* current = sdb->tables[i].entries->head;
             while (current != NULL) {
                 SDBEntry* next = current->next;
                 free(current->key);
                 free(current->value);
                 free(current);
                 current = next;
             }
             // Free hash table array
             free(sdb->tables[i].entries->entries);
             free(sdb->tables[i].entries);
         }
     }
 }
References SDBEntryList::entries, SDBTable::entries, SDBEntryList::head, SDBEntry::key, SDBTable::name, SDBEntry::next, SDB::table_count, SDB::tables, and SDBEntry::value.
sdb_table_find()
SDBTable* sdb_table_find (SDB * sdb, const char * name)
Finds a table in the database.
Parameters
sdb The database
name The name of the table
Returns
The table
Definition at line 560 of file sdb.h.
{
     for (int i = 0; i < sdb->table_count; i++) {
         if (strcmp(sdb->tables[i].name, name) == 0) {
             return &sdb->tables[i];
         }
     }
     return NULL;
 }
References SDBTable::name, SDB::table_count, and SDB::tables.
Referenced by sdb_table_get(), and sdb_table_set().
sdb_table_get()
char* sdb_table_get (SDB * sdb, const char * table, const char * key)
Gets a value from the database.
Parameters
sdb The database
table The name of the table
key The key
Returns
The value
Definition at line 616 of file sdb.h.
{
     SDBTable* t = sdb_table_find(sdb, table);
     if (t == NULL) {
         return NULL;
     }
     SDBEntry* e = t->entries->head;
     while (e != NULL) {
         if (strcmp(e->key, key) == 0) {
             return e->value;
         }
         e = e->next;
     }
     return NULL;
 }
References SDBTable::entries, SDBEntryList::head, SDBEntry::key, SDBEntry::next, sdb_table_find(), and SDBEntry::value.
Referenced by main().
sdb_table_set()
void sdb_table_set (SDB * sdb, const char * table, const char * key, const char * value)
Sets a value in the database.
Parameters
sdb The database
table The name of the table
key The key
value The value
Definition at line 580 of file sdb.h.
{
     SDBTable* t = sdb_table_find(sdb, table);
     if (!t) return;
     size_t hash = hash_string(key) % t->entries->capacity;
     SDBEntry* entry = t->entries->entries[hash];
     // Handle collision with linear probing
     while (entry && strcmp(entry->key, key) != 0) {
         hash = (hash + 1) % t->entries->capacity;
         entry = t->entries->entries[hash];
     }
     SDBEntry* e = (SDBEntry*)malloc(sizeof(SDBEntry));
     e->key = strdup(key);
     e->value = strdup(value);
     e->next = NULL;
     if (t->entries->head == NULL) {
         t->entries->head = e;
     } else {
         t->entries->tail->next = e;
     }
     t->entries->tail = e;
     sdb_save(sdb);
 }
References SDBEntryList::capacity, SDBEntryList::entries, SDBTable::entries, hash_string(), SDBEntryList::head, SDBEntry::key, SDBEntry::next, sdb_save(), sdb_table_find(), SDBEntryList::tail, and SDBEntry::value.
Referenced by main(), and sdb_batch_execute().
write_to_buffer()
static void write_to_buffer (unsigned char ** buffer, size_t * buffer_size, size_t * current_size, const void * data, size_t size) static
Helper function to write data to a buffer with automatic resizing.
Parameters
buffer Pointer to buffer pointer
buffer_size Pointer to current buffer size
current_size Pointer to current data size
data Data to write
size Size of data to write
Definition at line 655 of file sdb.h.
{
     // Check if we need to resize
     while (*current_size + size > *buffer_size) {
         *buffer_size *= 2;
         *buffer = (unsigned char*)realloc(*buffer, *buffer_size);
     }
     // Copy data to buffer
     memcpy(*buffer + *current_size, data, size);
     *current_size += size;
 }
Referenced by sdb_save().