name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Doxygen
        run: sudo apt-get install doxygen graphviz -y
        
      - name: Configure Doxygen
        run: |
          cat > Doxyfile << 'EOF'
          # Project settings
          PROJECT_NAME           = "SDB"
          PROJECT_NUMBER        = "0.4.0"
          PROJECT_BRIEF        = "A Simple Database Implementation in C"
          PROJECT_LOGO         = 
          
          # Output settings
          OUTPUT_DIRECTORY     = docs
          HTML_OUTPUT          = html
          
          # Input settings
          INPUT               = .
          FILE_PATTERNS       = *.c *.h
          RECURSIVE           = YES
          
          # HTML settings
          GENERATE_HTML       = YES
          HTML_COLORSTYLE    = DARK
          HTML_COLORSTYLE_HUE    = 220
          HTML_COLORSTYLE_SAT    = 100
          HTML_COLORSTYLE_GAMMA  = 80
          HTML_EXTRA_STYLESHEET  = 
          GENERATE_TREEVIEW  = YES
          DISABLE_INDEX      = NO
          FULL_SIDEBAR       = YES
          TREEVIEW_WIDTH     = 250
          
          # Layout
          LAYOUT_FILE        =
          DISABLE_INDEX      = NO
          GENERATE_TREEVIEW  = YES
          ENUM_VALUES_PER_LINE = 1
          TREEVIEW_WIDTH     = 250
          FULL_SIDEBAR       = YES
          
          # Appearance
          HIDE_UNDOC_RELATIONS = NO
          HAVE_DOT            = YES
          DOT_IMAGE_FORMAT    = svg
          INTERACTIVE_SVG     = YES
          DOT_TRANSPARENT     = YES
          DOT_MULTI_TARGETS   = YES
          GENERATE_LEGEND     = YES
          DOT_CLEANUP         = YES
          
          # Source code settings
          SOURCE_BROWSER     = YES
          INLINE_SOURCES    = YES
          REFERENCED_BY_RELATION = YES
          REFERENCES_RELATION    = YES
          REFERENCES_LINK_SOURCE = YES
          CALL_GRAPH            = YES
          CALLER_GRAPH          = YES
          
          # Other settings
          GENERATE_LATEX    = NO
          EXTRACT_ALL      = YES
          EXTRACT_PRIVATE  = YES
          EXTRACT_STATIC   = YES
          WARN_IF_UNDOCUMENTED = YES
          OPTIMIZE_OUTPUT_FOR_C = YES
          USE_MDFILE_AS_MAINPAGE = README.md
          MARKDOWN_SUPPORT = YES
          TOC_INCLUDE_HEADINGS = 5
          EOF
          
      - name: Generate Documentation
        run: doxygen Doxyfile
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/html
