name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Doxygen
        run: sudo apt-get install doxygen graphviz -y
        
      - name: Configure Doxygen
        run: |
          cat > Doxyfile << 'EOF'
          # Project settings
          PROJECT_NAME           = "SDB"
          PROJECT_NUMBER        = "0.4.0"
          PROJECT_BRIEF        = "A Simple Database Implementation in C"
          PROJECT_LOGO         = 
          
          # Output settings
          OUTPUT_DIRECTORY     = docs
          HTML_OUTPUT          = html
          
          # Input settings
          INPUT               = .
          FILE_PATTERNS       = *.c *.h
          RECURSIVE           = YES
          
          # HTML settings
          GENERATE_HTML       = YES
          HTML_COLORSTYLE    = DARK
          HTML_COLORSTYLE_HUE    = 209
          HTML_COLORSTYLE_SAT    = 255
          HTML_COLORSTYLE_GAMMA  = 113
          HTML_THEME            = "doxygen-awesome-css"
          
          # Download custom theme
          GENERATE_TREEVIEW      = YES
          DISABLE_INDEX         = NO
          FULL_SIDEBAR         = YES
          TREEVIEW_WIDTH       = 335
          
          # Layout
          LAYOUT_FILE        =
          ENUM_VALUES_PER_LINE = 1
          
          # Appearance
          HIDE_UNDOC_RELATIONS = NO
          HAVE_DOT            = YES
          DOT_IMAGE_FORMAT    = svg
          INTERACTIVE_SVG     = YES
          DOT_TRANSPARENT     = YES
          DOT_MULTI_TARGETS   = YES
          GENERATE_LEGEND     = YES
          DOT_CLEANUP         = YES
          
          # Source code settings
          SOURCE_BROWSER     = YES
          INLINE_SOURCES    = YES
          REFERENCED_BY_RELATION = YES
          REFERENCES_RELATION    = YES
          REFERENCES_LINK_SOURCE = YES
          CALL_GRAPH            = YES
          CALLER_GRAPH          = YES
          
          # Other settings
          GENERATE_LATEX    = NO
          EXTRACT_ALL      = YES
          EXTRACT_PRIVATE  = YES
          EXTRACT_STATIC   = YES
          WARN_IF_UNDOCUMENTED = YES
          OPTIMIZE_OUTPUT_FOR_C = YES
          USE_MDFILE_AS_MAINPAGE = README.md
          MARKDOWN_SUPPORT = YES
          TOC_INCLUDE_HEADINGS = 5
          
          # Modern features
          HTML_DYNAMIC_SECTIONS  = YES
          HTML_INDEX_NUM_ENTRIES = 100
          SEARCHENGINE           = YES
          SERVER_BASED_SEARCH    = NO
          EXTERNAL_SEARCH        = NO
          SEARCHDATA_FILE        = searchdata.xml
          GENERATE_DOCSET       = NO
          EOF
          
      # Add step to download and setup doxygen-awesome-css theme
      - name: Setup Doxygen Theme
        run: |
          mkdir -p docs/html/
          git clone https://github.com/jothepro/doxygen-awesome-css.git
          cp doxygen-awesome-css/doxygen-awesome.css docs/html/
          
      - name: Generate Documentation
        run: doxygen Doxyfile
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/html
